baseURL = 'https://sighery.com/'
locale = 'en-001'
title = 'Rincon'
theme = 'simplex'
copyright = '© 2025-2026 Sighery'
disableKinds = ['taxonomy', 'term', 'sitemap']

[module]
  [[module.mounts]]
    disableWatch = false
    source = 'content'
    target = 'content'
    files = [
      '! **/*.excalidraw'
    ]

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = 'RSS'
    # pageRef won't link it
    url = '/index.xml'
    weight = 20

  [[menus.main]]
    name = 'About'
    pageRef = '/about'
    weight = 30

[taxonomies]
  serie = 'series'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true

  [markup.highlight]
    style = 'monokai'
    hl_inline = false
    noClasses = false
    tabWidth = 4
    wrapperClass = 'highlight'


[params]
  description = 'Little corner where I write about things'

  # Footer section
  [[params.footer_links]]
    class = "sitemap"
    menuID = "main"

  [[params.footer_links]]
    class = "socials"

    [[params.footer_links.links]]
      name = "GitHub"
      link = "https://github.com/Sighery"
    [[params.footer_links.links]]
      name = "Twitch"
      link = "https://twitch.com/Sighery"
    [[params.footer_links.links]]
      name = "Twitter"
      link = "https://twitter.com/Sighery"

  [[params.footer_links]]
    class = "work"

    [[params.footer_links.links]]
      name = "LinkedIn"
      link = "https://www.linkedin.com/in/nicholas-tarta/"
    [[params.footer_links.links]]
      name = "Email"
      link = "mailto:contact@sighery.com"
